---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Deps
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install libsdl2-dev
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
    - name: cargo clippy 
      run: cargo clippy -- -D warnings

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ./target/release/dirtydmg-pc